apiVersion: v1
data:
  API_PORT: "8080"
  FRONTEND_PORT: "3000"
  NODE_ENV: development
  POSTGRES_DB: ticketing
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: ticketing_user
  QUEUE_NAME: ticket_orders
  REDIS_HOST: redis
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  name: app-config
